Changed track registry to be backed by forge controlled registry
CovertJaguar/Railcraft-API pull request #18
Opened 2017-05-16 20:02 UTC by liach

Resolves #17.
Will open a pull in Railcraft repo soon.

2017-05-17 00:02 UTC, CovertJaguar requested changes

2017-05-17 00:02 UTC, CovertJaguar commented on mods/railcraft/api/tracks/TrackRegistry.java
>          list.sort(Comparator.comparing(T::getName));
These can be removed, they were used to populate idMap

2017-05-17 00:04 UTC, liach commented on mods/railcraft/api/tracks/TrackRegistry.java
>          list.sort(Comparator.comparing(T::getName));
Didn't realize that. Will fix after updating intellij idea.

2017-05-17 08:16 UTC, CovertJaguar commented on mods/railcraft/api/tracks/TrackRegistry.java
> +        if (pass == 2) {
What is this is and how does it work? Why is this called multiple times?

2017-05-17 13:48 UTC, liach commented on mods/railcraft/api/tracks/TrackRegistry.java
> +        if (pass == 2) {
pass 1: one registry finalizes;
pass 2: the other finalizes.
After both registries are freezed, we build the list.

2017-05-17 16:44 UTC, CovertJaguar commented on mods/railcraft/api/tracks/TrackRegistry.java
> +        if (pass == 2) {
So what calls it the third time?

2017-05-17 16:46 UTC, CovertJaguar approved these changes

2017-05-17 16:49 UTC, CovertJaguar requested changes
You need to bump the API version number for this, probably a major revision from the looks of the missing functions.

2017-05-17 17:41 UTC, liach commented
Can I bump for both pulls?

2017-05-17 17:42 UTC, liach commented
Like a bump for 2 breaking changes

2017-05-17 17:47 UTC, CovertJaguar commented
Technically the other one, if implemented the way I say, is only an addition. But this one is breaking because you removed a method, so the Track Package info gets a major version bump.

But yeah you can consider a single bump good for both.

2017-05-18 01:44 UTC, CovertJaguar approved these changes

2017-05-18 01:45 UTC, merged