Fix outfitted track speed ignoring track type
CovertJaguar/Railcraft-API pull request #19
Opened 2017-05-17 02:04 UTC by liach

This allows track kits to determine the track type in order to handle the speed correctly. Added some reasonable annotations, too.

2017-05-17 08:06 UTC, CovertJaguar requested changes

2017-05-17 08:06 UTC, CovertJaguar commented on mods/railcraft/api/tracks/ITrackKitInstance.java
> +    default float getRailMaxSpeed(World world, @Nullable EntityMinecart cart, BlockPos pos, TrackType type) {
TrackType is totally not needed as a parameter.

2017-05-17 08:06 UTC, CovertJaguar commented on mods/railcraft/api/tracks/ITrackKitInstance.java
> +        return TrackToolsAPI.getTypeForTrackKitInstance(this);
```
return ((IOutfittedTrackTile)getTile()).getTrackType();
```

2017-05-17 08:06 UTC, CovertJaguar commented on mods/railcraft/api/tracks/ITrackKitInstance.java
> +        return type.getEventHandler().getMaxSpeed(world, cart, pos);
```
return getTrackType().getEventHandler().getMaxSpeed(world, cart, pos);
```

2017-05-17 08:06 UTC, CovertJaguar commented on mods/railcraft/api/tracks/TrackToolsAPI.java
> +    }
None of this is needed.

2017-05-17 13:47 UTC, liach commented on mods/railcraft/api/tracks/ITrackKitInstance.java
> +        return TrackToolsAPI.getTypeForTrackKitInstance(this);
The dummy tile will crash here

2017-05-17 16:43 UTC, CovertJaguar commented on mods/railcraft/api/tracks/ITrackKitInstance.java
> +        return TrackToolsAPI.getTypeForTrackKitInstance(this);
Why would it do that? Its designed to return the fallback TrackType.

2017-05-17 17:45 UTC, liach commented
Will fix them when I'm home.

2017-05-18 01:42 UTC, CovertJaguar approved these changes

2017-05-18 01:43 UTC, merged